#!/bin/bash

# GitHub Actions 部署助手
# 使用方法: bash scripts/deploy_guide.sh

echo "=========================================="
echo "GitHub Actions 外部触发 - 部署助手"
echo "=========================================="
echo ""

echo "📋 部署步骤清单："
echo ""
echo "【第一步】部署到 Render.com"
echo "  1. 访问 https://render.com 并用 GitHub 登录"
echo "  2. 点击 New → Web Service"
echo "  3. 连接此仓库"
echo "  4. 配置："
echo "     - Name: yang-daily-intelligence"
echo "     - Region: Oregon 或 Singapore"
echo "     - Build: pip install -r requirements.txt"
echo "     - Start: python src/main.py -m http -p \$PORT"
echo "     - Plan: Free"
echo "  5. 添加环境变量："
echo "     - COZE_API_KEY = <你的密钥>"
echo "     - PUSHPLUS_TOKEN = 8dec7824a9d74a1f8cf9738d55708f0b"
echo "  6. 点击 Create Web Service"
echo ""
echo "【第二步】获取服务 URL"
echo "  部署完成后，复制类似这样的地址："
echo "  https://yang-daily-intelligence.onrender.com"
echo ""
echo "【第三步】配置 GitHub Secrets"
echo "  1. 打开 GitHub 仓库"
echo "  2. Settings → Secrets → Actions"
echo "  3. 添加 secret："
echo "     Name: WORKFLOW_URL"
echo "     Value: https://你的地址.onrender.com/run"
echo ""
echo "【第四步】测试"
echo "  1. Actions → 每日认知情报推送"
echo "  2. Run workflow → Run workflow"
echo "  3. 查看日志，确认推送成功"
echo ""
echo "=========================================="
echo "定时配置: 每天北京时间 09:30 自动执行"
echo "=========================================="
